---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bggns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bgg-app
  template:
    metadata:
      name: bgg-app
      labels:
        app: bgg-app
    spec:
      containers:
      - name: bgg-backend
        image: stackupiss/bgg-backend:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: BGG_DB_USER
          valueFrom:
            configMapKeyRef:
              name: bggdb-cm
              key: bgg_db_user
        - name: BGG_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: bggdb-cm
              key: bgg_db_host
        - name: BGG_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bggdb-secret
              key: bgg_db_password
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
spec:
  selector:
    app: bgg-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3000
  type: NodePort