---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgg-db
  template:
    metadata:
      name: bgg-db
      labels:
        app: bgg-db
    spec:
      containers:
      - name: bgg-database
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
spec:
  selector:
    app: bgg-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP

---
apiVersion: v1
kind: Secret
metadata:
  name: bggdb-secret
  namespace: bggns
data:
  bgg_db_password: Y2hhbmdlaXQ=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bggdb-cm
  namespace: bggns
data:
  bgg_db_user: root
  bgg_db_host: bggdb-svc.bggns.svc.cluster.local